version: "3"

services:
    express-app:
        container_name: express-app
        build:
            context: ./server
            dockerfile: Dockerfile.bak
        env_file:
            - ./server/.env
        ports:
            - 5005:5005
        networks:
            - app-network

    file-uploader:
        container_name: file-uploader
        build:
            context: ./services/file-uploader
            dockerfile: Dockerfile.bak
        env_file:
            - ./services/file-uploader/.env
        ports:
            - 3555:3555
        networks:
            - app-network

    next-app:
        container_name: next-app
        build:
            context: ./client
            dockerfile: Dockerfile
        env_file:
            - ./client/.env
        volumes:
            - ./client/src:/app/src
            - ./client/public:/app/public
        ports:
            - 3000:3000
        networks:
            - app-network
        depends_on:
            - express-app
            - file-uploader

networks:
    app-network:
        external: true
